### ISSUE TITLE
Error: Failed to apply catalog: undefined method `http_ssl_instance' for Puppet::Network::HttpPool:Module

### ISSUE THREAD

**Issue by uder** [voxpupuli/puppet-vault_lookup#39]
Hello everyone,

I'm trying to use this module and get deprecation error. 

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.2.1
- Ruby: 
- Distribution: Centos 7
- Module version: 0.1.1

## How to reproduce (e.g Puppet code you use)
To check if module works, i'm trying to use code exact same with example in Readme. 

## What are you seeing
on line ```$d = Deferred('vault_lookup::lookup', ["secret/test", 'https://vault.hostname:8200'])```
agent falls and I see an error:

```Error: Failed to apply catalog: undefined method `http_ssl_instance' for Puppet::Network::HttpPool:Module
Did you mean?  http_instance```

Looks like, module's code uses a deprecated ruby's module. I'm not really familiar with ruby, so I can't inspect this issue closer. Is there any solution?

**Comment by kenyon** [comment]
There is no use of `http_ssl_instance` in this module, so that error must be coming from somewhere else.

**Comment by uder** [comment]
Hi Kenyon,

Thank you for an answer.

I have checked my setup once again and found the issue. 
I have installed module using command ```puppet module install puppet-vault_lookup```. Command installed 0.1.1 version of the module (v0.1.1 released Oct 16th 2018). So I get a pretty old version of the module. By the way, as I can see it is a last release in this repo and puppet forge 

Anyway, now I have taked module from repo and now it works! It prints another deprecation warning but works:
```Warning: The method 'Puppet::Network::HttpPool.http_instance' is deprecated. Use Puppet.runtime[:http] instead
   (file & line not available)
```

Could you make a new release to a puppet forge?

Kind Regards
Pavel Salnikov
