### ISSUE TITLE
Update function for work with Vault secured with Letsencrypt certificates

### ISSUE THREAD

**Issue by ntanaskovic** [voxpupuli/puppet-vault_lookup#44]
Hi there,

your function works well with Vault port secured with Puppet certificates, however we needed to use Vault with multiple Puppet masters. For that  I've made a fork of your repository, and updated it to use newer "HTTP::Client" library so that it will work with Vault secured with Letsencrypt certificates. I've tested it and can provide documentation as well. Can you please add me as a contributor, so that I can submit my changes as Pull Request ? I've created separate branch as "nikola".

Thanks

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.10.0
- Ruby:
- Distribution:
- Module version:

**Comment by ntanaskovic** [comment]
Hi Romain,

thank you for your reply.

I've never submitted any PRs to repos on Github, but I am using git
every day for my work where we have our own Gitea server. I am familiar
with the process as I am submitting PRs to our own repositories every
day by using Linux cli tools (git and vi). In short this is what I've
done, please review and let me know what I am doing wrong:

git clone https://github.com/voxpupuli/puppet-vault_lookup
cd puppet-vault_lookup
git branch nikola
git checkout nikola
... make changes, test etc

bundle exec rake lint
bundle exec rake validate
  ruby -c lib/puppet/functions/vault_lookup/lookup.rb
  Syntax OK
  ---> syntax:manifests
  ---> syntax:templates
  ---> syntax:hiera:yaml

Now I am ready to git push my changes and create PR, but I am getting
403 (denied)

git push --set-upstream origin nikola
  Username for 'https://github.com': ntanaskovic
  Password for ***@***.***':     (I am using my
Github token here)
  remote: Permission to voxpupuli/puppet-vault_lookup.git denied to
ntanaskovic.
  fatal: unable to access
'https://github.com/voxpupuli/puppet-vault_lookup/': The requested URL
returned error: 403

I appreciate your help with this.

Best regards

Nikola

**Comment by smortex** [comment]
Good start!

So you have a git repository which is a clone of ours and a branch with your work!  Next steps:

1. On https://github.com/voxpupuli/puppet-vault_lookup click on the "fork" button, this will create https://github.com/ntanaskovic/puppet-vault_lookup where you can push code;
2. In your repo add the remote (check that you have send your SSH key in GitHub settings.  If you prefer to type in passwords, you can use the https url…  both URL are visible by clicking on the "Code" green button on the page of your fork):
   git remote add ntanaskovic git@github.com:ntanaskovic/puppet-vault_lookup.git
3. Push your branch to your fork:
   git push -u ntanaskovic nikola
4. Open a Pull Request (I think that the post-commit message will contain the appropriate link).

Does this help?

**Comment by ntanaskovic** [comment]
Hi Romain,

did you get a chance to review my PR yet ? I know you guys are busy so 
if there is anything that I can do to help let me know please.

Best regards

Nikola
