### ISSUE TITLE
Detection of what kv version the vault is should be done via a different heuristic.

### ISSUE THREAD

**Issue by firstnevyn** [voxpupuli/puppet-vault_lookup#56]
While what's in place does work. it's restricted

You should be able to:
Allow retrieving a secret value from a kv1 vault secret engine
Allow retrieving a hash from a kv2 secret engine

The following api should be used to determine the kv version
https://support.hashicorp.com/hc/en-us/articles/4404288741139-Which-Version-is-my-Vault-KV-Mount-

**Comment by natemccurdy** [comment]
@firstnevyn I believe #76 solves for your first use case of retrieving a specific field from a kv1 engine.

**Comment by natemccurdy** [comment]
Re-reading the change from PR 76, and it covers both of your use cases.
This issue can be closed as it is fixed by #76
