### ISSUE TITLE
error: "client certificate must be supplied"

### ISSUE THREAD

**Issue by tam116** [voxpupuli/puppet-vault_lookup#57]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.16.0 (PE 2021.6.0)
- Ruby: bunlded PE
- Distribution: RHEL6 and RHEL8
- Module version: 0.5

## How to reproduce (e.g Puppet code you use)
Vault listener using Lets Encrypt cert
Vault listener config:      
 "tcp": {
        "address": "0.0.0.0:8201",
        "tls_disable": false,
        "tls_cert_file": "/etc/letsencrypt/live/vault/fullchain.pem",
        "tls_key_file": "/etc/letsencrypt/live/vault/privkey.pem",
        "tls_client_ca_file": "/etc/puppetlabs/puppet/ssl/certs/ca.pem",
      }
Run puppet agent -t with the code in readme

## What are you seeing
Puppet shows Error: Failed to apply catalog: Received 400 response code from vault at https://<vault-server>:8201/v1/auth/cert/login for authentication (api errors: ["client certificate must be supplied"])

However connecting via curl works as expected. I am able to get a auth token
curl --request POST --cert /etc/puppetlabs/puppet/ssl/certs/<agent_cert>.pem --key /etc/puppetlabs/puppet/ssl/private_keys/<agent_key>.pem --data '' -vvv https://<vault_server>:8201/v1/auth/cert/login

## What behaviour did you expect instead
For at least the authentication step to be completed

## Any additional information you'd like to impart
Vault audit log confirms the puppet isn't proceeding past the auth stage

The Puppet CA is the default config for PE, there is no external CA.

**Comment by tam116** [comment]
Further digging showed that this error was related to a bug in Puppet 7.16 and 6.27.1 which shipped with the latest versions of Puppet Enterprise at the time. Now that new versions of PE are available with newer Puppet agents that have the bug resolved there is no reason for this issue to remain open.

**Comment by Cajga** [comment]
Hi guys,

First of all thanks a lot for this module!

It would be nice if this issue with the known puppet versions could be mentioned in the [puppetserver-ca-and-agent-certificates](https://forge.puppet.com/modules/puppet/vault_lookup/readme#puppetserver-ca-and-agent-certificates) section of the Readme.

We are using RHEL9 and the latest package that Red Hat ships with Red Hat Satellite is puppet-agent-7.16.0-2.el9sat.x86_64 which has this bug. It took me quite some time (as our setup is pretty complex with an extra F5 LB cluster that terminates the TLS in front of 3 vault server cluster) to figure out what is the problem and I bet that there will be more and more people visiting this site in the near future (as 7.16 is the latest version in RHEL9).
