### ISSUE TITLE
tvpartytonight/vault_lookup migration

### ISSUE THREAD

**Issue by er0ck** [voxpupuli/puppet-vault_lookup#91]
- [x] [https://github.com/pcarlisle](@pcarlisle) added to the modules/admin team
- [x]   Repository transferred
- [x]   Github issues enabled
- [x]   Verify that all webhooks except travis are disabled
- [x]   Release a copy of your module to the ‘puppet’ forge account - to be done by @pcarlisle 
- [x]   Add the module to our modulesync setup
- [x]   Add the module to our plumbing repository(handles travis secrets)
- [x]   Ask an admin to add the collaborators team to the module’s Collaborators & Teams ‘Teams’ list with Write permissions
- [x]   Execute modulesync for this module
- [x]   Sync labels

**Comment by ekohl** [comment]
I see a module sync is update (even though https://github.com/voxpupuli/puppet-vault_lookup/pull/82 is quite old by now) and a release exists on https://forge.puppet.com/modules/puppet/vault_lookup. I can't find an old module to deprecate on the forge, so closing this.
